-- AlterTable
ALTER TABLE "Event" ADD COLUMN "global" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "vip" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN "prerequisiteText" TEXT;
